# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kalkulator(object):
    def setupUi(self, Kalkulator):
        Kalkulator.setObjectName("Kalkulator")
        Kalkulator.resize(391, 524)
        self.centralwidget = QtWidgets.QWidget(Kalkulator)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(50, 50, 271, 81))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 71, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_clicked)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 190, 71, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 190, 71, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 270, 71, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 270, 71, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 270, 71, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 350, 71, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 350, 71, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 350, 71, 61))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 420, 71, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(110, 420, 161, 61))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 190, 71, 61))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(290, 270, 71, 61))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(290, 350, 71, 61))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(290, 420, 71, 61))
        self.pushButton_15.setObjectName("pushButton_15")
        Kalkulator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Kalkulator)
        self.statusbar.setObjectName("statusbar")
        Kalkulator.setStatusBar(self.statusbar)

        self.retranslateUi(Kalkulator)
        QtCore.QMetaObject.connectSlotsByName(Kalkulator)

    def retranslateUi(self, Kalkulator):
        _translate = QtCore.QCoreApplication.translate
        Kalkulator.setWindowTitle(_translate("Kalkulator", "MainWindow"))
        self.pushButton.setText(_translate("Kalkulator", "7"))
        self.pushButton_2.setText(_translate("Kalkulator", "8"))
        self.pushButton_3.setText(_translate("Kalkulator", "9"))
        self.pushButton_4.setText(_translate("Kalkulator", "4"))
        self.pushButton_5.setText(_translate("Kalkulator", "5"))
        self.pushButton_6.setText(_translate("Kalkulator", "6"))
        self.pushButton_7.setText(_translate("Kalkulator", "1"))
        self.pushButton_8.setText(_translate("Kalkulator", "2"))
        self.pushButton_9.setText(_translate("Kalkulator", "3"))
        self.pushButton_10.setText(_translate("Kalkulator", "0"))
        self.pushButton_11.setText(_translate("Kalkulator", "="))
        self.pushButton_12.setText(_translate("Kalkulator", "/"))
        self.pushButton_13.setText(_translate("Kalkulator", "*"))
        self.pushButton_14.setText(_translate("Kalkulator", "-"))
        self.pushButton_15.setText(_translate("Kalkulator", "+"))

    def button_clicked(self):
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kalkulator = QtWidgets.QMainWindow()
    ui = Ui_Kalkulator()
    ui.setupUi(Kalkulator)
    Kalkulator.show()
    sys.exit(app.exec_())
